# isort: skip_file
from __future__ import annotations
import pandas as pd
import typing as ta


from bedrock.ceda_usa.transform.allocation.constants import EmissionsSource as ES
from bedrock.ceda_usa.transform.allocation.co2 import (
    # fmt: off
    allocate_electricity_generation as co2_allocate_electricity_generation,
    allocate_industrial_coal as co2_allocate_industrial_coal,
    allocate_industrial_natural_gas as co2_allocate_industrial_natural_gas,
    allocate_industrial_petrol as co2_allocate_industrial_petrol,
    allocate_transportation_aviation_gasoline as co2_allocate_transportation_aviation_gasoline,
    allocate_transportation_distillate_fuel_oil as co2_allocate_transportation_distillate_fuel_oil,
    allocate_transportation_jet_fuel as co2_allocate_transportation_jet_fuel,
    allocate_transportation_lpg as co2_allocate_transportation_lpg,
    allocate_transportation_motor_gasoline as co2_allocate_transportation_motor_gasoline,
    allocate_transportation_natural_gas as co2_allocate_transportation_natural_gas,
    allocate_transportation_residual_fuel as co2_allocate_transportation_residual_fuel,
    allocate_glass_production as co2_allocate_glass_production,
    allocate_lead_production as co2_allocate_lead_production,
    allocate_silicon_carbide_production_and_consumption as co2_allocate_silicon_carbide_production_and_consumption,
    allocate_zinc_production as co2_allocate_zinc_production,
    allocate_ferroalloy_production as co2_allocate_ferroalloy_production,
    allocate_phosphoric_acid_production as co2_allocate_phosphoric_acid_production,
    allocate_aluminum_production as co2_allocate_aluminum_production,
    allocate_ammonia_production as co2_allocate_ammonia_production,
    allocate_incineration_of_waste as co2_allocate_incineration_of_waste,
    allocate_lime_production as co2_allocate_lime_production,
    allocate_cement_production as co2_allocate_cement_production,
    allocate_titanium_dioxide_production as co2_allocate_titanium_dioxide_production,
    allocate_liming_of_agricultural_soils as co2_allocate_liming_of_agricultural_soils,
    allocate_iron_and_steel_production_and_metallurgical_coke_production as co2_allocate_iron_and_steel_production_and_metallurgical_coke_production,
    allocate_soda_ash_production_and_consumption as co2_allocate_soda_ash_production_and_consumption,
    allocate_natural_gas_systems as co2_allocate_natural_gas_systems,
    allocate_urea_fertilization as co2_allocate_urea_fertilization,
    allocate_urea_consumption_for_nonagricultural_purposes as co2_allocate_urea_consumption_for_nonagricultural_purposes,
    allocate_petrochemical_production as co2_allocate_petrochemical_production,
    allocate_petroleum_systems as co2_allocate_petroleum_systems,
    allocate_other_process_uses_of_carbonates as co2_allocate_other_process_uses_of_carbonates,
    allocate_commercial_coal as co2_allocate_commercial_coal,
    allocate_commercial_natural_gas as co2_allocate_commercial_natural_gas,
    allocate_commercial_petrol as co2_allocate_commercial_petrol,
    allocate_non_energy_fuels_coal_coke as co2_allocate_non_energy_fuels_coal_coke,
    allocate_non_energy_fuels_natural_gas as co2_allocate_non_energy_fuels_natural_gas,
    allocate_non_energy_fuels_petrol as co2_allocate_non_energy_fuels_petrol,
    allocate_non_energy_fuels_transport as co2_allocate_non_energy_fuels_transport,
    # fmt: on
)
from bedrock.ceda_usa.transform.allocation.ch4 import (
    # fmt: off
    allocate_abandoned_oil_and_gas_wells as ch4_allocate_abandoned_oil_and_gas_wells,
    allocate_abandoned_underground_coal_mines as ch4_allocate_abandoned_underground_coal_mines,
    allocate_coal_mining as ch4_allocate_coal_mining,
    allocate_composting as ch4_allocate_composting,
    allocate_enteric_fermentation as ch4_allocate_enteric_fermentation,
    allocate_field_burning_of_agricultural_residues as ch4_allocate_field_burning_of_agricultural_residues,
    allocate_landfills as ch4_allocate_landfills,
    allocate_manure_management as ch4_allocate_manure_management,
    allocate_mobile_combustion as ch4_allocate_mobile_combustion,
    allocate_natural_gas_systems as ch4_allocate_natural_gas_systems,
    allocate_petrochemical_production as ch4_allocate_petrochemical_production,
    allocate_petroleum_systems as ch4_allocate_petroleum_systems,
    allocate_rice_cultivation as ch4_allocate_rice_cultivation,
    allocate_stationary_combustion_commercial_fuel_oil as ch4_allocate_stationary_combustion_commercial_fuel_oil,
    allocate_stationary_combustion_commercial_natural_gas as ch4_allocate_stationary_combustion_commercial_natural_gas,
    allocate_stationary_combustion_electric as ch4_allocate_stationary_combustion_electric,
    allocate_wastewater_treatment as ch4_allocate_wastewater_treatment,
    allocate_stationary_combustion_industrial_coal as ch4_allocate_stationary_combustion_industrial_coal,
    allocate_stationary_combustion_industrial_fuel_oil as ch4_allocate_stationary_combustion_industrial_fuel_oil,
    allocate_stationary_combustion_industrial_natural_gas as ch4_allocate_stationary_combustion_industrial_natural_gas,
    # fmt: on
)
from bedrock.ceda_usa.transform.allocation.n2o import (
    # fmt: off
    allocate_adipic_acid as n2o_allocate_adipic_acid,
    allocate_caprolactam_glyoxal_and_glyoxylic_acid_production as n2o_allocate_caprolactam_glyoxal_and_glyoxylic_acid_production,
    allocate_composting as n2o_allocate_composting,
    allocate_fertilizer as n2o_allocate_fertilizer,
    allocate_field_burning_of_agricultural_residues as n2o_allocate_field_burning_of_agricultural_residues,
    allocate_incineration_of_waste as n2o_allocate_incineration_of_waste,
    allocate_international_bunker_fuels as n2o_allocate_international_bunker_fuels,
    allocate_manure_management as n2o_allocate_manure_management,
    allocate_mineralization as n2o_allocate_mineralization,
    allocate_nitric_acid as n2o_allocate_nitric_acid,
    allocate_product_uses as n2o_allocate_product_uses,
    allocate_semiconductor_manufacture as n2o_allocate_semiconductor_manufacture,
    allocate_soil_management_grassland as n2o_allocate_soil_management_grassland,
    allocate_stationary_combustion_commercial_fuel_oil as n2o_allocate_stationary_combustion_commercial_fuel_oil,
    allocate_stationary_combustion_commercial_natural_gas as n2o_allocate_stationary_combustion_commercial_natural_gas,
    allocate_stationary_combustion_electric as n2o_allocate_stationary_combustion_electric,
    allocate_stationary_combustion_residential as n2o_allocate_stationary_combustion_residential,
    allocate_wastewater_treatment as n2o_allocate_wastewater_treatment,
    allocate_industrial_coal as n2o_allocate_industrial_coal,
    allocate_industrial_fuel_oil as n2o_allocate_industrial_fuel_oil,
    allocate_industrial_natural_gas as n2o_allocate_industrial_natural_gas,
    allocate_mobile_combustion as n2o_allocate_mobile_combustion,
    # fmt: on
)

from bedrock.ceda_usa.transform.allocation.other_gases import (
    # fmt: off
    allocate_hfc_125_foams,
    allocate_hfc_125_others,
    allocate_hfc_125_transport,
    allocate_hfc_134a_foams,
    allocate_hfc_134a_magnesium_production,
    allocate_hfc_134a_others,
    allocate_hfc_134a_transport,
    allocate_hfc_143a_foams,
    allocate_hfc_143a_others,
    allocate_hfc_143a_transport,
    allocate_hfc_23_hcfc_22_production,
    allocate_hfc_23_semiconductor_manufacture,
    allocate_hfc_236fa_foams,
    allocate_hfc_236fa_others,
    allocate_hfc_236fa_transport,
    allocate_hfc_32_foams,
    allocate_hfc_32_others,
    allocate_hfc_32_transport,
    allocate_nf3_semiconductor_manufacture,
    allocate_pfc_c2f6_aluminum_production,
    allocate_pfc_c2f6_semiconductor_manufacture,
    allocate_pfc_c3f8_semiconductor_manufacture,
    allocate_pfc_c4f8_semiconductor_manufacture,
    allocate_pfc_cf4_aluminum_production,
    allocate_pfc_cf4_semiconductor_manufacture,
    allocate_sf6_electricity,
    allocate_sf6_magnesium_production,
    allocate_sf6_semiconductor_manufacture,
    # fmt: on
)
from bedrock.ceda_usa.utils.taxonomy.bea.ceda_v7 import CEDA_V7_SECTORS


def zero_allocator() -> pd.Series[float]:
    # for cases where there are no emissions to allocate
    return pd.Series(0.0, index=CEDA_V7_SECTORS)


ALLOCATED_EMISSIONS_REGISTRY: ta.Dict[ES, ta.Callable[[], pd.Series[float]]] = {
    # CO2
    ES.co2_aluminum_production: co2_allocate_aluminum_production,
    ES.co2_ammonia_production: co2_allocate_ammonia_production,
    ES.co2_carbon_dioxide_consumption: zero_allocator,
    ES.co2_cement_production: co2_allocate_cement_production,
    ES.co2_commercial_coal: co2_allocate_commercial_coal,
    ES.co2_commercial_natural_gas: co2_allocate_commercial_natural_gas,
    ES.co2_commercial_petrol: co2_allocate_commercial_petrol,
    ES.co2_electricity_generation: co2_allocate_electricity_generation,
    ES.co2_ferroalloy_production: co2_allocate_ferroalloy_production,
    ES.co2_glass_production: co2_allocate_glass_production,
    ES.co2_incineration_of_waste: co2_allocate_incineration_of_waste,
    ES.co2_industrial_coal: co2_allocate_industrial_coal,
    ES.co2_industrial_natural_gas: co2_allocate_industrial_natural_gas,
    ES.co2_industrial_petrol: co2_allocate_industrial_petrol,
    ES.co2_international_bunker_fuels: zero_allocator,
    ES.co2_iron_and_steel_production_and_metallurgical_coke_production: co2_allocate_iron_and_steel_production_and_metallurgical_coke_production,
    ES.co2_land_use_land_use_change_and_forestry_sinks: zero_allocator,
    ES.co2_lead_production: co2_allocate_lead_production,
    ES.co2_lime_production: co2_allocate_lime_production,
    ES.co2_liming_of_agricultural_soils: co2_allocate_liming_of_agricultural_soils,
    ES.co2_magnesium_production_and_processing: zero_allocator,
    ES.co2_natural_gas_systems: co2_allocate_natural_gas_systems,
    ES.co2_non_energy_fuels_coal_coke: co2_allocate_non_energy_fuels_coal_coke,
    ES.co2_non_energy_fuels_natural_gas: co2_allocate_non_energy_fuels_natural_gas,
    ES.co2_non_energy_fuels_petrol: co2_allocate_non_energy_fuels_petrol,
    ES.co2_non_energy_fuels_transport: co2_allocate_non_energy_fuels_transport,
    ES.co2_other_process_uses_of_carbonates: co2_allocate_other_process_uses_of_carbonates,
    ES.co2_peatlands_remaining_peatlands: zero_allocator,
    ES.co2_petrochemical_production: co2_allocate_petrochemical_production,
    ES.co2_petroleum_systems: co2_allocate_petroleum_systems,
    ES.co2_phosphoric_acid_production: co2_allocate_phosphoric_acid_production,
    ES.co2_residential: zero_allocator,
    ES.co2_silicon_carbide_production_and_consumption: co2_allocate_silicon_carbide_production_and_consumption,
    ES.co2_soda_ash_production_and_consumption: co2_allocate_soda_ash_production_and_consumption,
    ES.co2_titanium_dioxide_production: co2_allocate_titanium_dioxide_production,
    ES.co2_transportation_aviation_gasoline: co2_allocate_transportation_aviation_gasoline,
    ES.co2_transportation_distillate_fuel_oil: co2_allocate_transportation_distillate_fuel_oil,
    ES.co2_transportation_jet_fuel: co2_allocate_transportation_jet_fuel,
    ES.co2_transportation_lpg: co2_allocate_transportation_lpg,
    ES.co2_transportation_motor_gasoline: co2_allocate_transportation_motor_gasoline,
    ES.co2_transportation_natural_gas: co2_allocate_transportation_natural_gas,
    ES.co2_transportation_residual_fuel: co2_allocate_transportation_residual_fuel,
    ES.co2_urea_consumption_for_nonagricultural_purposes: co2_allocate_urea_consumption_for_nonagricultural_purposes,
    ES.co2_urea_fertilization: co2_allocate_urea_fertilization,
    ES.co2_us_territories: zero_allocator,
    ES.co2_wood_biomass_and_ethanol_consumption: zero_allocator,
    ES.co2_zinc_production: co2_allocate_zinc_production,
    # CH4
    ES.ch4_abandoned_oil_and_gas_wells: ch4_allocate_abandoned_oil_and_gas_wells,
    ES.ch4_abandoned_underground_coal_mines: ch4_allocate_abandoned_underground_coal_mines,
    ES.ch4_coal_mining: ch4_allocate_coal_mining,
    ES.ch4_composting: ch4_allocate_composting,
    ES.ch4_enteric_fermentation: ch4_allocate_enteric_fermentation,
    ES.ch4_ferroalloy_production: zero_allocator,
    ES.ch4_field_burning_of_agricultural_residues: ch4_allocate_field_burning_of_agricultural_residues,
    ES.ch4_incineration_of_waste: zero_allocator,
    ES.ch4_international_bunker_fuels: zero_allocator,
    ES.ch4_iron_and_steel_production_and_metallurgical_coke_production: zero_allocator,
    ES.ch4_landfills: ch4_allocate_landfills,
    ES.ch4_manure_management: ch4_allocate_manure_management,
    ES.ch4_mobile_combustion: ch4_allocate_mobile_combustion,
    ES.ch4_natural_gas_systems: ch4_allocate_natural_gas_systems,
    ES.ch4_petrochemical_production: ch4_allocate_petrochemical_production,
    ES.ch4_petroleum_systems: ch4_allocate_petroleum_systems,
    ES.ch4_rice_cultivation: ch4_allocate_rice_cultivation,
    ES.ch4_silicon_carbide_production_and_consumption: zero_allocator,
    ES.ch4_stationary_combustion_commercial_fuel_oil: ch4_allocate_stationary_combustion_commercial_fuel_oil,
    ES.ch4_stationary_combustion_commercial_natural_gas: ch4_allocate_stationary_combustion_commercial_natural_gas,
    ES.ch4_stationary_combustion_electric: ch4_allocate_stationary_combustion_electric,
    ES.ch4_stationary_combustion_industrial_coal: ch4_allocate_stationary_combustion_industrial_coal,
    ES.ch4_stationary_combustion_industrial_fuel_oil: ch4_allocate_stationary_combustion_industrial_fuel_oil,
    ES.ch4_stationary_combustion_industrial_natural_gas: ch4_allocate_stationary_combustion_industrial_natural_gas,
    ES.ch4_stationary_combustion_residential: zero_allocator,
    ES.ch4_wastewater_treatment: ch4_allocate_wastewater_treatment,
    # N2O
    ES.n2o_adipic_acid_production: n2o_allocate_adipic_acid,
    ES.n2o_agricultural_soil_management_cropland_fertilizer: n2o_allocate_fertilizer,
    ES.n2o_agricultural_soil_management_cropland_mineralization_and_other: n2o_allocate_mineralization,
    ES.n2o_agricultural_soil_management_grassland: n2o_allocate_soil_management_grassland,
    ES.n2o_caprolactam_glyoxal_and_glyoxylic_acid_production: n2o_allocate_caprolactam_glyoxal_and_glyoxylic_acid_production,
    ES.n2o_composting: n2o_allocate_composting,
    ES.n2o_field_burning_of_agricultural_residues: n2o_allocate_field_burning_of_agricultural_residues,
    ES.n2o_from_product_uses: n2o_allocate_product_uses,
    ES.n2o_incineration_of_waste: n2o_allocate_incineration_of_waste,
    ES.n2o_international_bunker_fuels: n2o_allocate_international_bunker_fuels,
    ES.n2o_manure_management: n2o_allocate_manure_management,
    ES.n2o_mobile_combustion: n2o_allocate_mobile_combustion,
    ES.n2o_nitric_acid_production: n2o_allocate_nitric_acid,
    ES.n2o_semiconductor_manufacture: n2o_allocate_semiconductor_manufacture,
    ES.n2o_stationary_combustion_commercial_fuel_oil: n2o_allocate_stationary_combustion_commercial_fuel_oil,
    ES.n2o_stationary_combustion_commercial_natural_gas: n2o_allocate_stationary_combustion_commercial_natural_gas,
    ES.n2o_stationary_combustion_electric: n2o_allocate_stationary_combustion_electric,
    ES.n2o_stationary_combustion_industrial_coal: n2o_allocate_industrial_coal,
    ES.n2o_stationary_combustion_industrial_fuel_oil: n2o_allocate_industrial_fuel_oil,
    ES.n2o_stationary_combustion_industrial_natural_gas: n2o_allocate_industrial_natural_gas,
    ES.n2o_stationary_combustion_residential: n2o_allocate_stationary_combustion_residential,
    ES.n2o_wastewater_treatment: n2o_allocate_wastewater_treatment,
    # OTHER GASES
    ES.hfc_125_foams: allocate_hfc_125_foams,
    ES.hfc_125_substitution_of_ozone_depleting_substances_others: allocate_hfc_125_others,
    ES.hfc_125_substitution_of_ozone_depleting_substances_transport: allocate_hfc_125_transport,
    ES.hfc_134a_foams: allocate_hfc_134a_foams,
    ES.hfc_134a_magnesium_production_and_processing: allocate_hfc_134a_magnesium_production,
    ES.hfc_134a_substitution_of_ozone_depleting_substances_others: allocate_hfc_134a_others,
    ES.hfc_134a_substitution_of_ozone_depleting_substances_transport: allocate_hfc_134a_transport,
    ES.hfc_143a_foams: allocate_hfc_143a_foams,
    ES.hfc_143a_substitution_of_ozone_depleting_substances_others: allocate_hfc_143a_others,
    ES.hfc_143a_substitution_of_ozone_depleting_substances_transport: allocate_hfc_143a_transport,
    ES.hfc_23_hcfc_22_production: allocate_hfc_23_hcfc_22_production,
    ES.hfc_23_semiconductor_manufacture: allocate_hfc_23_semiconductor_manufacture,
    ES.hfc_236fa_foams: allocate_hfc_236fa_foams,
    ES.hfc_236fa_substitution_of_ozone_depleting_substances_others: allocate_hfc_236fa_others,
    ES.hfc_236fa_substitution_of_ozone_depleting_substances_transport: allocate_hfc_236fa_transport,
    ES.hfc_32_foams: allocate_hfc_32_foams,
    ES.hfc_32_substitution_of_ozone_depleting_substances_others: allocate_hfc_32_others,
    ES.hfc_32_substitution_of_ozone_depleting_substances_transport: allocate_hfc_32_transport,
    ES.nf3_semiconductor_manufacture: allocate_nf3_semiconductor_manufacture,
    ES.pfc_c2f6_aluminum_production: allocate_pfc_c2f6_aluminum_production,
    ES.pfc_c2f6_semiconductor_manufacture: allocate_pfc_c2f6_semiconductor_manufacture,
    ES.pfc_c3f8_semiconductor_manufacture: allocate_pfc_c3f8_semiconductor_manufacture,
    ES.pfc_c4f8_semiconductor_manufacture: allocate_pfc_c4f8_semiconductor_manufacture,
    ES.pfc_cf4_aluminum_production: allocate_pfc_cf4_aluminum_production,
    ES.pfc_cf4_semiconductor_manufacture: allocate_pfc_cf4_semiconductor_manufacture,
    ES.sf6_electrical_transmission_and_distribution: allocate_sf6_electricity,
    ES.sf6_magnesium_production_and_processing: allocate_sf6_magnesium_production,
    ES.sf6_semiconductor_manufacture: allocate_sf6_semiconductor_manufacture,
}
