# isort: skip_file
# fmt: off
from .industrial_coal import allocate_industrial_coal  # noqa: F401
from .industrial_natural_gas import allocate_industrial_natural_gas  # noqa: F401
from .industrial_petrol import allocate_industrial_petrol  # noqa: F401
from .electricity_generation import allocate_electricity_generation  # noqa: F401
from .transportation_aviation_gasoline import allocate_transportation_aviation_gasoline  # noqa: F401
from .transportation_distillate_fuel_oil import allocate_transportation_distillate_fuel_oil  # noqa: F401
from .transportation_jet_fuel import allocate_transportation_jet_fuel  # noqa: F401
from .transportation_motor_gasoline import allocate_transportation_motor_gasoline  # noqa: F401
from .transportation_residual_fuel import allocate_transportation_residual_fuel  # noqa: F401
from .transportation_lpg import allocate_transportation_lpg  # noqa: F401
from .transportation_natural_gas import allocate_transportation_natural_gas  # noqa: F401
from .glass_production import allocate_glass_production  # noqa: F401
from .lead_production import allocate_lead_production  # noqa: F401
from .silicon_carbide_production_and_consumption import allocate_silicon_carbide_production_and_consumption  # noqa: F401
from .phosphoric_acid_production import allocate_phosphoric_acid_production  # noqa: F401
from .zinc_production import allocate_zinc_production  # noqa: F401
from .ferroalloy_production import allocate_ferroalloy_production  # noqa: F401
from .aluminum_production import allocate_aluminum_production  # noqa: F401
from .ammonia_production import allocate_ammonia_production  # noqa: F401
from .incineration_of_waste import allocate_incineration_of_waste  # noqa: F401
from .lime_production import allocate_lime_production  # noqa: F401
from .cement_production import allocate_cement_production  # noqa: F401
from .titanium_dioxide_production import allocate_titanium_dioxide_production  # noqa: F401
from .liming_of_agricultural_soils import allocate_liming_of_agricultural_soils  # noqa: F401
from .iron_and_steel_production_and_metallurgical_coke_production import allocate_iron_and_steel_production_and_metallurgical_coke_production  # noqa: F401
from .soda_ash_production_and_consumption import allocate_soda_ash_production_and_consumption  # noqa: F401
from .petroleum_systems import allocate_petroleum_systems  # noqa: F401
from .natural_gas_systems import allocate_natural_gas_systems  # noqa: F401
from .urea_fertilization import allocate_urea_fertilization  # noqa: F401
from .urea_consumption_for_nonagricultural_purposes import allocate_urea_consumption_for_nonagricultural_purposes  # noqa: F401
from .petrochemical_production import allocate_petrochemical_production  # noqa: F401
from .other_process_uses_of_carbonates import allocate_other_process_uses_of_carbonates  # noqa: F401
from .non_energy_fuels_coal_coke import allocate_non_energy_fuels_coal_coke  # noqa: F401
from .non_energy_fuels_natural_gas import allocate_non_energy_fuels_natural_gas  # noqa: F401
from .non_energy_fuels_petrol import allocate_non_energy_fuels_petrol  # noqa: F401
from .non_energy_fuels_transport import allocate_non_energy_fuels_transport  # noqa: F401
from .commercial_coal import allocate_commercial_coal  # noqa: F401
from .commercial_natrual_gas import allocate_commercial_natural_gas  # noqa: F401
from .commercial_petrol import allocate_commercial_petrol  # noqa: F401
