# This config is used to run the Cornerstone 2026 model schema on the 2025 USA data with waste disaggregation enabled.

#####
# Model base settings
#####

#####
# Data selection
#####

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: True
implement_waste_disaggregation: True

#####
# Bugfix
#####

#####
# Baseline snapshot
#####
snapshot_version_or_git_sha: "a0e514e361bb0a87cd40b68b1eccc8bb911fa35c"
