# This config is used to run the Cornerstone 2026 model schema on the 2025 USA data with waste disaggregation enabled.

#####
# Model base settings
#####

#####
# Data selection
#####

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: True
implement_waste_disaggregation: True

#####
# Bugfix
#####

#####
# Baseline snapshot
#####
snapshot_version_or_git_sha: "9fe22d9afdfdb6806397b2356eb3cf4c4c346744"
