# CEDA 2023 FBS with FLOWSA-aligned liming (proportional via BEA 327400).
# GHG Model is GHG_national_Cornerstone_2023_ag_soils

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: true
update_liming_and_fertilizer_ghg_method: true
snapshot_version_or_git_sha: "ff3c5a0ea73b26cecd09fd0613b8b34e1f30bcdc"
