# Use Cornerstone 2020 GHG FBS (GHG_national_Cornerstone_2020)
# Pipeline loads E from flowsa.

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: true
ghg_2020: true
