# CEDA 2023 FBS with FLOWSA-aligned liming (proportional via BEA 327400).
# GHG Model is GHG_national_Cornerstone_2023_ag_soils

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: true
update_liming_and_fertilizer_ghg_method: true
snapshot_version_or_git_sha: "9fe22d9afdfdb6806397b2356eb3cf4c4c346744"
