# Fully impelmented Cornerstone 2025 model
# Use Cornerstone 2023 UMD GHG FBS (GHG_national_Cornerstone_2023_umd_ghgia) via v0_3_umd_ghgia
# Relies on published UMD GHGIA data (rather than EPA GHGI)
# Pipeline loads E from flowsa.
# Transform B matrix with USEEIO method
# Implement waste disaggregation.

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: true
v0_3_umd_ghgia: true
use_E_data_year_for_x_in_B: True
implement_waste_disaggregation: True
cornerstone_industry_avg_margins: True
