# Use Cornerstone 2023 FBS with other_gases method.
# Requires load_E_from_flowsa and update_other_gases_ghg_method so the pipeline loads E from flowsa with the other_gases method.

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: true
update_other_gases_ghg_method: true
snapshot_version_or_git_sha: "ff3c5a0ea73b26cecd09fd0613b8b34e1f30bcdc"
