# Use Cornerstone 2023 FBS with other_gases method.
# Requires load_E_from_flowsa and update_other_gases_ghg_method so the pipeline loads E from flowsa with the other_gases method.
# GHG Model is GHG_national_Cornerstone_2023_other_gases

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: true
update_other_gases_ghg_method: true
snapshot_version_or_git_sha: "a0e514e361bb0a87cd40b68b1eccc8bb911fa35c"
