# Use Cornerstone 2023 GHG FBS - updated CEDA 2023 GHG FBS method.
# Pipeline loads E from flowsa.

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: true
new_ghg_method: true
