# Use CEDA 2023 FBS with FLOWSA-aligned enteric fermentation and manure management.
# Pulls manure management N2O directly from T_5_7 instead of T_2_1 proportional attribution.
# GHG Model is GHG_national_Cornerstone_2023_ag_livestock

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: true
update_enteric_fermentation_and_manure_management_ghg_method: true
snapshot_version_or_git_sha: "a0e514e361bb0a87cd40b68b1eccc8bb911fa35c"
