# Use CEDA 2023 FBS with fuel-specific electricity activities.
# Maintains CEDA approach of attribution to single NAICS 2211.
# Requires load_E_from_flowsa and update_electricity_ghg_method so the pipeline loads E from flowsa with the electricity method.

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
load_E_from_flowsa: true
update_electricity_ghg_method: true
snapshot_version_or_git_sha: "a0e514e361bb0a87cd40b68b1eccc8bb911fa35c"
