#####
# Model base settings
#####
model_base_year: 2023

#####
# Data selection
#####
usa_ghg_data_year: 2023

#####
# Baseline snapshot
#####
snapshot_version_or_git_sha: "2ebb51f7190c3a62b5d8b2420bff9b20f57282fc"
