#####
# Model base settings
#####
model_base_year: 2023

#####
# Data selection
#####
usa_ghg_data_year: 2023

#####
# Baseline snapshot
#####
snapshot_version_or_git_sha: "a0e514e361bb0a87cd40b68b1eccc8bb911fa35c"
