#####
# Model base settings
#####
model_base_year: 2023

#####
# Data selection
#####
usa_ghg_data_year: 2023

#####
# Baseline snapshot
#####
snapshot_version_or_git_sha: "5f32e53941e58023a331ef9f3df46e8834891aa2"
