from __future__ import annotations

import typing as ta

"""
NOTE: table numbers change year-over-year in the GHG inventory report.
For updates, refer to the documentation in each function for the contents of the table,
and find the updated table number in the latest GHG inventory.
"""
TBL_NUMBERS_2022 = ta.Literal[
    "2-1",
    "3-8",
    "3-9",
    "3-14",
    "3-15",
    "3-23",
    "3-24",
    "3-44",
    "3-46",
    "3-73",
    "3-75",
    "4-51",
    "4-55",
    "4-103",
    "4-121",
    "4-125",
    "4-127",
    "5-3",
    "5-6",
    "5-17",
    "5-18",
    "5-29",
    "A-4",
    "A-5",
    "A-68",
    "A-89",
]

TBL_NUMBERS_2023 = ta.Literal[
    "2-1",
    "3-8",
    "3-9",
    "3-14",
    "3-15",
    "3-25",
    "3-45",
    "3-47",
    "3-64",
    "3-66",
    "4-51",
    "4-55",
    "4-100",
    "4-118",
    "4-122",
    "4-124",
    "5-3",
    "5-7",
    "5-18",
    "5-19",
    "5-29",
    "A-5",
    "A-69",
    "A-90",
]

TBL_NUMBERS = ta.Union[TBL_NUMBERS_2022, TBL_NUMBERS_2023]

EPA_TABLE_NAMES = ta.Literal[
    "recent_trends_in_ghg_emissions_and_sinks",
    "ch4_stationary_combustion",
    "n2o_stationary_combustion",
    "ch4_mobile_combustion",
    "n2o_mobile_combustion",
    "co2_fossil_fuel_non_energy_uses",
    "ch4_petroleum_systems",
    "co2_petroleum_systems",
    "ch4_natural_gas_systems",
    "co2_natural_gas_systems",
    "co2_soda_ash_production",
    "co2_ch4_petrochemical_production",
    "pfc_aluminum_production",
    "pfc_hfc_sf6_nf3_n2o_semiconductor_manufacture",
    "hfc_ods_substitutes",
    "hfc_pfc_emissions_ods_substitutes_by_sector",
    "ch4_enteric_fermentation",
    "ch4_n2o_manure_management",
    "direct_n2o_agricultural_soils",
    "indirect_n2o_agricultural_soils",
    "ch4_n2o_field_burning",
    "energy_consumption_co2_by_fuel_type",
    "fuel_consumption_by_vehicle_type",
    "hfc_transportation_sources",
]

EPA_TABLE_NAME_TO_TABLE_NUMBER_MAP_2022: ta.Dict[EPA_TABLE_NAMES, TBL_NUMBERS_2022] = {
    "recent_trends_in_ghg_emissions_and_sinks": "2-1",
    "ch4_stationary_combustion": "3-8",
    "n2o_stationary_combustion": "3-9",
    "ch4_mobile_combustion": "3-14",
    "n2o_mobile_combustion": "3-15",
    "co2_fossil_fuel_non_energy_uses": "3-24",
    "ch4_petroleum_systems": "3-44",
    "co2_petroleum_systems": "3-46",
    "ch4_natural_gas_systems": "3-73",
    "co2_natural_gas_systems": "3-75",
    "co2_soda_ash_production": "4-51",
    "co2_ch4_petrochemical_production": "4-55",
    "pfc_aluminum_production": "4-103",
    "pfc_hfc_sf6_nf3_n2o_semiconductor_manufacture": "4-121",
    "hfc_ods_substitutes": "4-125",
    "hfc_pfc_emissions_ods_substitutes_by_sector": "4-127",
    "ch4_enteric_fermentation": "5-3",
    "ch4_n2o_manure_management": "5-6",
    "direct_n2o_agricultural_soils": "5-17",
    "indirect_n2o_agricultural_soils": "5-18",
    "ch4_n2o_field_burning": "5-29",
    "energy_consumption_co2_by_fuel_type": "A-5",
    "fuel_consumption_by_vehicle_type": "A-68",
    "hfc_transportation_sources": "A-89",
}

EPA_TABLE_NAME_TO_TABLE_NUMBER_MAP_2023: ta.Dict[EPA_TABLE_NAMES, TBL_NUMBERS_2023] = {
    "recent_trends_in_ghg_emissions_and_sinks": "2-1",
    "ch4_stationary_combustion": "3-8",
    "n2o_stationary_combustion": "3-9",
    "ch4_mobile_combustion": "3-14",
    "n2o_mobile_combustion": "3-15",
    "co2_fossil_fuel_non_energy_uses": "3-25",
    "ch4_petroleum_systems": "3-45",
    "co2_petroleum_systems": "3-47",
    "ch4_natural_gas_systems": "3-64",
    "co2_natural_gas_systems": "3-66",
    "co2_soda_ash_production": "4-51",
    "co2_ch4_petrochemical_production": "4-55",
    "pfc_aluminum_production": "4-100",
    "pfc_hfc_sf6_nf3_n2o_semiconductor_manufacture": "4-118",
    "hfc_ods_substitutes": "4-122",
    "hfc_pfc_emissions_ods_substitutes_by_sector": "4-124",
    "ch4_enteric_fermentation": "5-3",
    "ch4_n2o_manure_management": "5-7",
    "direct_n2o_agricultural_soils": "5-18",
    "indirect_n2o_agricultural_soils": "5-19",
    "ch4_n2o_field_burning": "5-29",
    "energy_consumption_co2_by_fuel_type": "A-5",
    "fuel_consumption_by_vehicle_type": "A-69",
    "hfc_transportation_sources": "A-90",
}
