"""
Tests for the ``Margins_Transport_<year>`` FBS (#611, nowcast step 4c).

The fast tests here check the crosswalks and the clean functions. The
``eeio_integration`` ones generate the method and check that it reproduces
``nowcast_transport_margins`` - which is the property that justifies having two
paths to the same numbers at all.
"""

from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import pandas as pd
import pytest

import bedrock.transform.iot.nowcast_transport_margins as tm
from bedrock.transform.flowbysector import getFlowBySector
from bedrock.transform.margins import transport
from bedrock.utils.config.settings import crosswalkpath

MAPPING_DIR = Path(tm.TRUCK_CROSSWALK_PATH).parent
ANCHOR = 2017

#: The five commodities that *give* transport margin up. None of them may be a
#: crosswalk target: BEA publishes zero transport margin received by all five.
MODE_CODES = set(tm.MODE_COMMODITIES.values())


def _sector_crosswalk(source: str) -> pd.DataFrame:
    return pd.read_csv(crosswalkpath / f'Sector_Crosswalk_{source}.csv', dtype=str)


# --------------------------------------------------------------------------
# the crosswalks the FBS reads
# --------------------------------------------------------------------------


@pytest.mark.parametrize('source', ['Census_SAS', 'STB_CRSR', 'BTS_FAF'])
def test_sector_crosswalk_targets_bea_detail_commodities(source: str) -> None:
    """
    Every target is a BEA 2017 code the published margins table knows.

    The method's target schema is BEA detail, so a NAICS code or a typo here
    would not fail - it would just never match, and the activity's margin would
    quietly vanish into the renormalisation.
    """
    crosswalk = _sector_crosswalk(source)
    published = tm.published_transport_by_commodity()
    unknown = set(crosswalk['Sector']) - set(published.index)
    assert not unknown, f'{source} targets non-commodity codes {sorted(unknown)}'
    assert set(crosswalk['SectorSourceName']) == {'BEA_2017_Code'}


@pytest.mark.parametrize('source', ['Census_SAS', 'STB_CRSR', 'BTS_FAF'])
def test_no_mode_delivers_margin_to_a_transport_commodity(source: str) -> None:
    """
    A mode may not hand margin to another mode.

    BEA publishes zero transport margin *received* by all five transport
    commodities, and ``transport_margin_column`` raises if a code turns up on
    both sides of the column. Catching it in the crosswalk says which file to
    fix instead of only that something is wrong.
    """
    assert not (set(_sector_crosswalk(source)['Sector']) & MODE_CODES)


@pytest.mark.parametrize('source', ['Census_SAS', 'STB_CRSR', 'BTS_FAF'])
def test_every_target_receives_published_transport_margin(source: str) -> None:
    """
    A target with no published ``TRANS`` cannot hold a share.

    The within-group weight *is* the published column, so an activity mapped
    only to zero-weight commodities has nowhere to put its margin and is
    silently dropped. The rail crosswalk writer already guards this; the guard
    belongs on all three.
    """
    crosswalk = _sector_crosswalk(source)
    published = tm.published_transport_by_commodity()
    weight = crosswalk['Sector'].map(published).fillna(0.0)
    stranded = sorted(
        set(
            crosswalk.loc[
                weight.groupby(crosswalk['Activity']).transform('sum') <= 0, 'Activity'
            ]
        )
    )
    assert not stranded, f'{source} activities with no weighted target: {stranded}'


def test_sector_crosswalks_are_a_faithful_re_emission() -> None:
    """
    The ``Sector_Crosswalk_*`` files still match the crosswalks they came from.

    They are generated by ``write_margins_sector_crosswalks.py`` and hold no
    judgement of their own, so an edit to a source crosswalk that was not
    followed by a re-run would leave the FBS and the module disagreeing about
    which commodity an activity serves - the exact failure the two-path design
    is meant to make visible.
    """
    rail_source = tm.load_rail_crosswalk()
    rail_source = rail_source[rail_source['bea_2017_commodity'] != '']
    rail_emitted = _sector_crosswalk('STB_CRSR')
    assert set(zip(rail_source['stcc5'], rail_source['bea_2017_commodity'])) == set(
        zip(rail_emitted['Activity'], rail_emitted['Sector'])
    )

    truck_source = tm.load_truck_crosswalk()
    truck_source = truck_source[truck_source['sas_group'] != tm.TRUCK_OTHER_GOODS]
    pipeline_source = tm.load_pipeline_crosswalk()
    sas_emitted = _sector_crosswalk('Census_SAS')
    assert set(
        zip(truck_source['sas_group'], truck_source['bea_2017_commodity'])
    ) | set(
        zip(pipeline_source['sas_naics'], pipeline_source['bea_2017_commodity'])
    ) == set(
        zip(sas_emitted['Activity'], sas_emitted['Sector'])
    )

    faf_source = tm.load_faf_sctg_crosswalk()
    faf_emitted = _sector_crosswalk('BTS_FAF')
    assert set(zip(faf_source['sctg'], faf_source['bea_2017_commodity'])) == set(
        zip(faf_emitted['Activity'], faf_emitted['Sector'])
    )


def test_every_allocator_key_is_in_the_crosswalk() -> None:
    """
    Every key the clean function emits can be mapped.

    An unmapped key is not an error in the machinery - it is dropped, and the
    remaining keys renormalise over its share. That is the quiet failure this
    catches.
    """
    keys = {
        'Census_SAS': set(
            tm.load_truck_group_revenue(ANCHOR)
            .drop(index=tm.TRUCK_OTHER_GOODS, errors='ignore')
            .index
        )
        | set(tm.load_pipeline_item_revenue(ANCHOR).index),
        'BTS_FAF': set(tm.load_faf_ton_miles('Water', ANCHOR).index),
    }
    for source, activity_keys in keys.items():
        mapped = set(_sector_crosswalk(source)['Activity'])
        assert not activity_keys - mapped, (
            f'{source} allocator keys missing from the crosswalk: '
            f'{sorted(activity_keys - mapped)}'
        )


# --------------------------------------------------------------------------
# the clean functions
# --------------------------------------------------------------------------


def test_flowable_names_every_mode() -> None:
    """The Flowable is the transport commodity's name, so all five need one."""
    assert set(transport.FLOWABLE) == set(tm.MODE_COMMODITIES)


def test_clean_parameter_must_name_a_mode() -> None:
    """
    A missing or misspelled ``clean_parameter`` has to raise, not default.

    It selects both the allocator and the control total, so a set that fell
    through to a default would allocate one mode's revenue against another
    mode's level and still balance.
    """
    for bad in (None, 'trucking', '484000'):
        with pytest.raises(ValueError, match='clean_parameter'):
            transport._mode(SimpleNamespace(config={'clean_parameter': bad}))


def test_a_mixed_year_activity_set_raises() -> None:
    """One control total cannot be applied to two years of shape."""
    fba = pd.DataFrame({'Year': ['2017', '2018'], 'FlowAmount': [1.0, 1.0]})
    with pytest.raises(ValueError, match='single year'):
        transport._year(fba)


def test_volume_allocator_applies_the_difficulty_multiplier() -> None:
    """
    Weighted ton-miles are not raw ton-miles.

    The 1/2/3 multiplier is the one part of the water and air method that is
    BEA's own construction rather than ours, so it has to actually reach the
    allocator.
    """
    raw = tm.load_faf_ton_miles('Water', ANCHOR)
    weighted = transport._volume_allocator('water', ANCHOR)
    assert set(weighted.index) == set(raw.index)
    assert (weighted >= raw).all()
    shares_raw = raw / raw.sum()
    shares_weighted = weighted / weighted.sum()
    assert not shares_raw.round(6).equals(shares_weighted.round(6))


def test_rail_allocator_drops_the_excluded_codes() -> None:
    """
    The service-class and empty-move codes never reach the FBS.

    They are 16.3% of released 2017 revenue, ``46111`` trailer-on-flatcar alone
    being 14.0%, and they name no commodity. Keeping them in the crosswalk file
    with a blank target is what makes the exclusion visible; this checks the FBS
    honours it rather than mapping them somewhere.
    """
    crosswalk = tm.load_rail_crosswalk()
    excluded = set(crosswalk.loc[crosswalk['bea_2017_commodity'] == '', 'stcc5'])
    assert excluded
    assert not set(transport._rail_allocator(ANCHOR).index) & excluded


def test_truck_allocator_drops_other_goods() -> None:
    """
    "Other goods" is 32.4% of 2017 motor carrier revenue and carries no

    commodity information. BEA drops it and lets the rest renormalise, and says
    so explicitly, so this is the method rather than an approximation of it.
    """
    allocator = tm.load_truck_group_revenue(ANCHOR).drop(
        index=tm.TRUCK_OTHER_GOODS, errors='ignore'
    )
    assert tm.TRUCK_OTHER_GOODS not in allocator.index
    assert len(allocator) == 10


# --------------------------------------------------------------------------
# the generated method
# --------------------------------------------------------------------------


@pytest.fixture(scope='module')
def fbs_2017() -> pd.DataFrame:
    return getFlowBySector(f'Margins_Transport_{ANCHOR}', download_FBAs_if_missing=True)


@pytest.mark.eeio_integration
def test_each_mode_reaches_its_own_control_total(fbs_2017: pd.DataFrame) -> None:
    """
    2017 is an identity: every mode reproduces its published give-up exactly.

    The coverage ratio is that give-up over the same year's freight revenue, so
    anything other than an exact match means the FBS lost or double-counted
    part of the allocator between the clean function and aggregation.
    """
    got = fbs_2017.groupby('SectorConsumedBy')['FlowAmount'].sum()
    for mode, commodity in tm.MODE_COMMODITIES.items():
        assert got[commodity] == pytest.approx(
            tm._mode_give_up_2017(commodity), rel=1e-9
        ), mode


@pytest.mark.eeio_integration
def test_the_column_is_the_published_transport_total(fbs_2017: pd.DataFrame) -> None:
    """
    The five modes together are the published column, to publication rounding.

    The give-up side totals 415,548 million against a receiving side of 414,559
    - 0.24% - which is rounding on the receiving side of the published Margins
    table, not a modelling gap. The FBS is built from the give-up side, so it
    lands above the receiving side by exactly that.
    """
    published = tm.published_transport_by_commodity().sum()
    built = fbs_2017['FlowAmount'].sum()
    assert built == pytest.approx(published, rel=0.0025)
    assert built > published


@pytest.mark.eeio_integration
def test_no_commodity_receives_margin_from_itself(fbs_2017: pd.DataFrame) -> None:
    """A transport commodity may not appear on the receiving side."""
    assert not set(fbs_2017['SectorProducedBy']) & MODE_CODES


@pytest.mark.eeio_integration
def test_the_fbs_reproduces_the_module_per_commodity(fbs_2017: pd.DataFrame) -> None:
    """
    The two paths to the same numbers agree, which is what makes both keepable.

    CAUTION: they agree to about 0.3%, not exactly, and the reason is worth
    knowing: the within-group weight is the published 2017 transport margin, and
    the FBS reads it off ``BEA_Detail_Supply``'s ``TRANS`` column - published in
    whole millions - while the module sums it out of the Margins transaction
    table, which is finer. Same quantity, different publication rounding. Any
    drift larger than that is a real divergence.
    """
    module = tm.mode_allocations(ANCHOR)
    for mode, commodity in tm.MODE_COMMODITIES.items():
        built = (
            fbs_2017[fbs_2017['SectorConsumedBy'] == commodity]
            .groupby('SectorProducedBy')['FlowAmount']
            .sum()
        )
        expected = module[mode]
        joined = pd.DataFrame({'fbs': built, 'module': expected}).fillna(0.0)
        drift = (joined['fbs'] - joined['module']).abs().sum() / expected.sum()
        assert drift < 0.005, f'{mode} drifts {drift:.2%} from the module'


@pytest.mark.eeio_integration
def test_a_nowcast_year_moves_off_the_anchor() -> None:
    """
    A non-anchor year builds, carries its own year, and is not 2017 again.

    The per-year files are one line over a shared method, so ``year`` reaching
    each source by inheritance is the whole mechanism - if it did not, every
    year would silently rebuild the anchor.
    """
    fbs = getFlowBySector('Margins_Transport_2022', download_FBAs_if_missing=True)
    assert set(fbs['Year'].astype(int)) == {2022}
    got = fbs.groupby('SectorConsumedBy')['FlowAmount'].sum()
    for mode, commodity in tm.MODE_COMMODITIES.items():
        assert got[commodity] == pytest.approx(
            tm.mode_control_total(mode, 2022), rel=1e-9
        )
        assert got[commodity] != pytest.approx(tm._mode_give_up_2017(commodity))
