# some convenience imports
import typing as ta

GHG_LITERAL = ta.Literal["CO2", "CH4", "N2O", "HFCs", "PFCs", "SF6", "NF3"]
GHG: ta.List[GHG_LITERAL] = list(ta.get_args(GHG_LITERAL))
GHG_DETAILED = [
    # order matters!
    "CO2",
    "CH4",
    "N2O",
    "HFC-23",
    "HFC-32",
    "HFC-125",
    "HFC-134a",
    "HFC-143a",
    "HFC-236fa",
    "CF4",
    "C2F6",
    "C3F8",
    "C4F8",
    "SF6",
    "NF3",
]

GHG_MAPPING = {  # GHG->GHG_DETAILED
    # order matters!
    "CO2": ["CO2"],
    "CH4": ["CH4"],
    "N2O": ["N2O"],
    "HFCs": ["HFC-23", "HFC-32", "HFC-125", "HFC-134a", "HFC-143a", "HFC-236fa"],
    "PFCs": ["CF4", "C2F6", "C3F8", "C4F8"],
    "SF6": ["SF6"],
    "NF3": ["NF3"],
}

CEDA_EMISSIONS_SOURCES = [
    "co2_electricity_generation",
    "co2_transportation_natural_gas",
    "co2_transportation_aviation_gasoline",
    "co2_transportation_distillate_fuel_oil",
    "co2_transportation_jet_fuel",
    "co2_transportation_lpg",
    "co2_transportation_motor_gasoline",
    "co2_transportation_residual_fuel",
    "co2_industrial_coal",
    "co2_industrial_natural_gas",
    "co2_industrial_petrol",
    "co2_residential",
    "co2_commercial_coal",
    "co2_commercial_natural_gas",
    "co2_commercial_petrol",
    "co2_us_territories",
    "co2_non_energy_fuels_coal_coke",
    "co2_non_energy_fuels_natural_gas",
    "co2_non_energy_fuels_petrol",
    "co2_non_energy_fuels_transport",
    "co2_iron_and_steel_production_and_metallurgical_coke_production",
    "co2_natural_gas_systems",
    "co2_cement_production",
    "co2_petrochemical_production",
    "co2_lime_production",
    "co2_ammonia_production",
    "co2_incineration_of_waste",
    "co2_petroleum_systems",
    "co2_liming_of_agricultural_soils",
    "co2_urea_consumption_for_nonagricultural_purposes",
    "co2_other_process_uses_of_carbonates",
    "co2_urea_fertilization",
    "co2_aluminum_production",
    "co2_soda_ash_production_and_consumption",
    "co2_ferroalloy_production",
    "co2_titanium_dioxide_production",
    "co2_zinc_production",
    "co2_phosphoric_acid_production",
    "co2_glass_production",
    "co2_carbon_dioxide_consumption",
    "co2_peatlands_remaining_peatlands",
    "co2_lead_production",
    "co2_silicon_carbide_production_and_consumption",
    "co2_magnesium_production_and_processing",
    "co2_land_use_land_use_change_and_forestry_sinks",
    "co2_wood_biomass_and_ethanol_consumption",
    "co2_international_bunker_fuels",
    "ch4_enteric_fermentation",
    "ch4_natural_gas_systems",
    "ch4_landfills",
    "ch4_manure_management",
    "ch4_coal_mining",
    "ch4_petroleum_systems",
    "ch4_wastewater_treatment",
    "ch4_rice_cultivation",
    "ch4_stationary_combustion_electric",
    "ch4_stationary_combustion_industrial_coal",
    "ch4_stationary_combustion_industrial_fuel_oil",
    "ch4_stationary_combustion_industrial_natural_gas",
    "ch4_stationary_combustion_commercial_fuel_oil",
    "ch4_stationary_combustion_commercial_natural_gas",
    "ch4_stationary_combustion_residential",
    "ch4_abandoned_oil_and_gas_wells",
    "ch4_abandoned_underground_coal_mines",
    "ch4_mobile_combustion",
    "ch4_composting",
    "ch4_field_burning_of_agricultural_residues",
    "ch4_petrochemical_production",
    "ch4_ferroalloy_production",
    "ch4_silicon_carbide_production_and_consumption",
    "ch4_iron_and_steel_production_and_metallurgical_coke_production",
    "ch4_incineration_of_waste",
    "ch4_international_bunker_fuels",
    "n2o_agricultural_soil_management_cropland_fertilizer",
    "n2o_agricultural_soil_management_cropland_mineralization_and_other",
    "n2o_agricultural_soil_management_grassland",
    "n2o_stationary_combustion_electric",
    "n2o_stationary_combustion_industrial_coal",
    "n2o_stationary_combustion_industrial_fuel_oil",
    "n2o_stationary_combustion_industrial_natural_gas",
    "n2o_stationary_combustion_commercial_fuel_oil",
    "n2o_stationary_combustion_commercial_natural_gas",
    "n2o_stationary_combustion_residential",
    "n2o_mobile_combustion",
    "n2o_manure_management",
    "n2o_nitric_acid_production",
    "n2o_adipic_acid_production",
    "n2o_wastewater_treatment",
    "n2o_from_product_uses",
    "n2o_caprolactam_glyoxal_and_glyoxylic_acid_production",
    "n2o_composting",
    "n2o_incineration_of_waste",
    "n2o_semiconductor_manufacture",
    "n2o_field_burning_of_agricultural_residues",
    "n2o_international_bunker_fuels",
    "hfc_32_substitution_of_ozone_depleting_substances_transport",
    "hfc_125_substitution_of_ozone_depleting_substances_transport",
    "hfc_134a_substitution_of_ozone_depleting_substances_transport",
    "hfc_143a_substitution_of_ozone_depleting_substances_transport",
    "hfc_236fa_substitution_of_ozone_depleting_substances_transport",
    "hfc_32_substitution_of_ozone_depleting_substances_others",
    "hfc_125_substitution_of_ozone_depleting_substances_others",
    "hfc_134a_substitution_of_ozone_depleting_substances_others",
    "hfc_143a_substitution_of_ozone_depleting_substances_others",
    "hfc_236fa_substitution_of_ozone_depleting_substances_others",
    "hfc_32_foams",
    "hfc_125_foams",
    "hfc_134a_foams",
    "hfc_143a_foams",
    "hfc_236fa_foams",
    "hfc_23_hcfc_22_production",
    "hfc_23_semiconductor_manufacture",
    "hfc_134a_magnesium_production_and_processing",
    "pfc_cf4_aluminum_production",
    "pfc_c2f6_aluminum_production",
    "pfc_cf4_semiconductor_manufacture",
    "pfc_c2f6_semiconductor_manufacture",
    "pfc_c3f8_semiconductor_manufacture",
    "pfc_c4f8_semiconductor_manufacture",
    "sf6_electrical_transmission_and_distribution",
    "sf6_magnesium_production_and_processing",
    "sf6_semiconductor_manufacture",
    "nf3_semiconductor_manufacture",
]
