## Config for model 3 in Reconciling Data Years study
# Use IOT as is to make the A matrix in 2017 dollars and use annual GHG data with annual output to make the B matrix; then deflate the B matrix to IOT year (2017)

use_useeio_B: true
scale_a_matrix_with_useeio_method: true #necessary not to inflate or scale A 
apply_inflation_to_V: false
