#!/bin/bash

# Exit if any command fails
set -e

gcloud config set project cornerstone-data
gcloud auth application-default login --scopes=openid,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/drive
