# isort: skip_file
# fmt: off
from .hfc_125_foams import allocate_hfc_125_foams  # noqa: F401
from .hfc_125_others import allocate_hfc_125_others  # noqa: F401
from .hfc_125_transport import allocate_hfc_125_transport  # noqa: F401
from .hfc_134a_foams import allocate_hfc_134a_foams  # noqa: F401
from .hfc_134a_magnesium_production import allocate_hfc_134a_magnesium_production  # noqa: F401
from .hfc_134a_others import allocate_hfc_134a_others  # noqa: F401
from .hfc_134a_transport import allocate_hfc_134a_transport  # noqa: F401
from .hfc_143a_foams import allocate_hfc_143a_foams  # noqa: F401
from .hfc_143a_others import allocate_hfc_143a_others  # noqa: F401
from .hfc_143a_transport import allocate_hfc_143a_transport  # noqa: F401
from .hfc_236fa_foams import allocate_hfc_236fa_foams  # noqa: F401
from .hfc_236fa_others import allocate_hfc_236fa_others  # noqa: F401
from .hfc_236fa_transport import allocate_hfc_236fa_transport  # noqa: F401
from .hfc_23_hcfc_22_production import allocate_hfc_23_hcfc_22_production  # noqa: F401
from .hfc_23_semiconductor_manufacture import allocate_hfc_23_semiconductor_manufacture  # noqa: F401
from .hfc_32_foams import allocate_hfc_32_foams  # noqa: F401
from .hfc_32_others import allocate_hfc_32_others  # noqa: F401
from .hfc_32_transport import allocate_hfc_32_transport  # noqa: F401
from .nf3_semiconductor_manufacture import allocate_nf3_semiconductor_manufacture  # noqa: F401
from .pfc_c2f6_aluminum_production import allocate_pfc_c2f6_aluminum_production  # noqa: F401
from .pfc_c2f6_semiconductor_manufacture import allocate_pfc_c2f6_semiconductor_manufacture  # noqa: F401
from .pfc_c3f8_semiconductor_manufacture import allocate_pfc_c3f8_semiconductor_manufacture  # noqa: F401
from .pfc_c4f8_semiconductor_manufacture import allocate_pfc_c4f8_semiconductor_manufacture  # noqa: F401
from .pfc_cf4_aluminum_production import allocate_pfc_cf4_aluminum_production  # noqa: F401
from .pfc_cf4_semiconductor_manufacture import allocate_pfc_cf4_semiconductor_manufacture  # noqa: F401
from .sf6_electricity import allocate_sf6_electricity  # noqa: F401
from .sf6_magnesium_production import allocate_sf6_magnesium_production  # noqa: F401
from .sf6_semiconductor_manufacture import allocate_sf6_semiconductor_manufacture  # noqa: F401
