# some convenience imports
import typing as ta

CEDA_COUNTRY = ta.Literal[
    # ORDER MATTERS
    "AUS",
    "AUT",
    "BEL",
    "CAN",
    "CHL",
    "COL",
    "CRI",
    "CZE",
    "DNK",
    "EST",
    "FIN",
    "FRA",
    "DEU",
    "GRC",
    "HUN",
    "ISL",
    "IRL",
    "ISR",
    "ITA",
    "JPN",
    "KOR",
    "LVA",
    "LTU",
    "LUX",
    "MEX",
    "NLD",
    "NZL",
    "NOR",
    "POL",
    "PRT",
    "SVK",
    "SVN",
    "ESP",
    "SWE",
    "CHE",
    "TUR",
    "GBR",
    "USA",
    "ARG",
    "BRA",
    "BGR",
    "KHM",
    "CHN",
    "HRV",
    "CYP",
    "IND",
    "IDN",
    "HKG",
    "KAZ",
    "LAO",
    "MYS",
    "MLT",
    "MAR",
    "MMR",
    "PER",
    "PHL",
    "ROU",
    "RUS",
    "SAU",
    "SGP",
    "ZAF",
    "TWN",
    "THA",
    "TUN",
    "VNM",
    "AFG",
    "AGO",
    "ALB",
    "ARE",
    "ATG",
    "BDI",
    "BEN",
    "BFA",
    "BGD",
    "BHR",
    "BHS",
    "BLZ",
    "BOL",
    "BRB",
    "BTN",
    "CAF",
    "CIV",
    "CMR",
    "COG",
    "DMA",
    "DOM",
    "DZA",
    "ECU",
    "EGY",
    "ETH",
    "FJI",
    "GAB",
    "GIN",
    "GMB",
    "GNB",
    "GNQ",
    "GRD",
    "GTM",
    "HND",
    "HTI",
    "IRN",
    "IRQ",
    "JAM",
    "JOR",
    "KEN",
    "KIR",
    "KNA",
    "KWT",
    "LBN",
    "LCA",
    "LKA",
    "LSO",
    "MDA",
    "MDV",
    "MKD",
    "MLI",
    "MNG",
    "MUS",
    "MWI",
    "NAM",
    "NER",
    "NGA",
    "NIC",
    "NPL",
    "NRU",
    "OMN",
    "PAK",
    "PNG",
    "PRY",
    "QAT",
    "RWA",
    "SEN",
    "SLB",
    "SLE",
    "SLV",
    "SWZ",
    "SYC",
    "TCD",
    "TGO",
    "TLS",
    "TTO",
    "TZA",
    "UGA",
    "UKR",
    "URY",
    "VCT",
    "VUT",
    "WSM",
    "ROW",
]

CEDA_COUNTRIES: ta.List[CEDA_COUNTRY] = list(ta.get_args(CEDA_COUNTRY))

CEDA_COUNTRY_MAPPING = {
    # order matters!
    # source: https://www.iban.com/country-codes
    "AUS": "AU",
    "AUT": "AT",
    "BEL": "BE",
    "CAN": "CA",
    "CHL": "CL",
    "COL": "CO",
    "CRI": "CR",
    "CZE": "CZ",
    "DNK": "DK",
    "EST": "EE",
    "FIN": "FI",
    "FRA": "FR",
    "DEU": "DE",
    "GRC": "GR",
    "HUN": "HU",
    "ISL": "IS",
    "IRL": "IE",
    "ISR": "IL",
    "ITA": "IT",
    "JPN": "JP",
    "KOR": "KR",
    "LVA": "LV",
    "LTU": "LT",
    "LUX": "LU",
    "MEX": "MX",
    "NLD": "NL",
    "NZL": "NZ",
    "NOR": "NO",
    "POL": "PL",
    "PRT": "PT",
    "SVK": "SK",
    "SVN": "SI",
    "ESP": "ES",
    "SWE": "SE",
    "CHE": "CH",
    "TUR": "TR",
    "GBR": "GB",
    "USA": "US",
    "ARG": "AR",
    "BRA": "BR",
    "BGR": "BG",
    "KHM": "KH",
    "CHN": "CN",
    "HRV": "HR",
    "CYP": "CY",
    "IND": "IN",
    "IDN": "ID",
    "HKG": "HK",
    "KAZ": "KZ",
    "LAO": "LA",
    "MYS": "MY",
    "MLT": "MT",
    "MAR": "MA",
    "MMR": "MM",
    "PER": "PE",
    "PHL": "PH",
    "ROU": "RO",
    "RUS": "RU",
    "SAU": "SA",
    "SGP": "SG",
    "ZAF": "ZA",
    "TWN": "TW",
    "THA": "TH",
    "TUN": "TN",
    "VNM": "VN",
    "AFG": "AF",
    "AGO": "AO",
    "ALB": "AL",
    "ARE": "AE",
    "ATG": "AG",
    "BDI": "BI",
    "BEN": "BJ",
    "BFA": "BF",
    "BGD": "BD",
    "BHR": "BH",
    "BHS": "BS",
    "BLZ": "BZ",
    "BOL": "BO",
    "BRB": "BB",
    "BTN": "BT",
    "CAF": "CF",
    "CIV": "CI",
    "CMR": "CM",
    "COG": "CG",
    "DMA": "DM",
    "DOM": "DO",
    "DZA": "DZ",
    "ECU": "EC",
    "EGY": "EG",
    "ETH": "ET",
    "FJI": "FJ",
    "GAB": "GA",
    "GIN": "GN",
    "GMB": "GM",
    "GNB": "GW",
    "GNQ": "GQ",
    "GRD": "GD",
    "GTM": "GT",
    "HND": "HN",
    "HTI": "HT",
    "IRN": "IR",
    "IRQ": "IQ",
    "JAM": "JM",
    "JOR": "JO",
    "KEN": "KE",
    "KIR": "KI",
    "KNA": "KN",
    "KWT": "KW",
    "LBN": "LB",
    "LCA": "LC",
    "LKA": "LK",
    "LSO": "LS",
    "MDA": "MD",
    "MDV": "MV",
    "MKD": "MK",
    "MLI": "ML",
    "MNG": "MN",
    "MUS": "MU",
    "MWI": "MW",
    "NAM": "NA",
    "NER": "NE",
    "NGA": "NG",
    "NIC": "NI",
    "NPL": "NP",
    "NRU": "NR",
    "OMN": "OM",
    "PAK": "PK",
    "PNG": "PG",
    "PRY": "PY",
    "QAT": "QA",
    "RWA": "RW",
    "SEN": "SN",
    "SLB": "SB",
    "SLE": "SL",
    "SLV": "SV",
    "SWZ": "SZ",
    "SYC": "SC",
    "TCD": "TD",
    "TGO": "TG",
    "TLS": "TL",
    "TTO": "TT",
    "TZA": "TZ",
    "UGA": "UG",
    "UKR": "UA",
    "URY": "UY",
    "VCT": "VC",
    "VUT": "VU",
    "WSM": "WS",
    "ROW": "ROW",
}
